### ISSUE TITLE
oneset和gater

### ISSUE THREAD

**Issue by zpp13** [jiacheng-ye/kg_gater#2]
首先对作者的工作表示敬意，之前就关注过one2set，请问作者有用gater+one2set一起做过实验吗？因为我理解的是：gater的主要工作是encoder，one2set的工作主要是decoder，理论上结合起来会有更好的效果吧？非常期待作者的回答
最后感谢作者的开源精神。

**Comment by jiacheng-ye** [comment]
对的 两者是complementary的

**Comment by zpp13** [comment]
那请问您有做过两者一起的试验吗？可以说一下试验结果吗？

**Comment by jiacheng-ye** [comment]
这个之前没有做~
